services:
  file_handler:
    build: src
    command: uvicorn src.file_handler.api:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8008:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "TZ=${TIMEZONE}"
    ports:
      - "5432:5432"

volumes:
  db-data: